# Generated by Django 2.2.2 on 2019-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=250)),
                ('is_completed', models.BooleanField(default=False, help_text='The task is completed or not.')),
                ('is_deleted', models.BooleanField(default=False, help_text='The task is deleted for the user or not.')),
                ('serial_number', models.PositiveIntegerField(default=1, help_text='How the task is order')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, help_text='When the task is deleted by the user', null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
                'ordering': ['serial_number', '-create_at'],
            },
        ),
    ]
